
---
- name: Create RKE2 master config
  template:
    src: rke2_master_config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Start and enable RKE2 server
  systemd:
    name: rke2-server
    state: started
    enabled: yes

- name: Wait for RKE2 to generate kubeconfig
  wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    state: present
    timeout: 600

- name: Copy kubeconfig to user directory
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: 0600
