
---
- name: Install Keepalived
  include_role:
    name: geerlingguy.keepalived

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start and enable Keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes
